# adapted from: https://github.com/Cyb3r-Jak3/html5validator-action/wiki/Getting-Started
name: HTML Validation

on:
  push:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        blacklist: documentation
    - name: create issue on failed workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Action HTML checking workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
        assignees: claireellul