name: Javascript Unit Tests
on:
  push:
    branches:
  pull_request:
    branch: [main]   
  workflow_dispatch:

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm run test

